### ISSUE TITLE
[Bug] LUA error since 11.0

### ISSUE THREAD

**Issue by BloodWolfe** [Starlynk1/IncognitoResurrected#5] opened 2024-07-31 13:53 UTC
I get the following error when the addon is enabled and am unable to use the addon.

Message: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1950: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
Time: Wed Jul 31 09:51:00 2024
Count: 1
Stack: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1950: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/IncognitoResurrected/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:529: in function `InitializeAddon'
[string "@Interface/AddOns/IncognitoResurrected/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:644: in function <...ognitoResurrected/Libs/AceAddon-3.0/AceAddon-3.0.lua:636>

Locals: arg1 = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "IncognitoResurrected"
 orderedModules = <table> {
 }
 baseName = "IncognitoResurrected"
 hooks = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleState = true
}

**Comment by Starlynk1** [comment] 2024-07-31 17:29
Thanks for the report, I am unable to reproduce this so it may be a little longer to figure out.

Have you tried disabling all other addons and having only Incognito running? For now, it may seem that another addon is interfering with it.

Either way, I am trying to get to the bottom of it and get it fixed asap.

**Comment by Starlynk1** [comment] 2024-08-01 00:16
I did an update just a moment ago, not specific for this issue, but please try it and see if that fixes it. Your errors are realted to the options window it appears, so good chance it may be resolved. If I don't hear back after the weekend, I will close this as resolved.

**Comment by nickylogic** [comment] 2024-08-01 00:38
I see the same error as reported above, even with the most recent update.  It looks like Blizzard deprecated an API .. hate when that happens :( https://github.com/Gethe/wow-ui-source/blob/6454953db99468d576438ddeb72c812268a0d145/Interface/SharedXML/Settings/Blizzard_Deprecated.lua#L4

**Comment by BloodWolfe** [comment] 2024-08-01 13:19
Just tried now and same error still.

**Comment by Starlynk1** [comment] 2024-08-01 15:00
> I see the same error as reported above, even with the most recent update. It looks like Blizzard deprecated an API .. hate when that happens :( https://github.com/Gethe/wow-ui-source/blob/6454953db99468d576438ddeb72c812268a0d145/Interface/SharedXML/Settings/Blizzard_Deprecated.lua#L4

Yup, weird thing is it doesn't error out on my end, so not sure why that is. May be that I have Ace3 installed seperately or some other addon that makes it not error out. Working on update now.

**Comment by Starlynk1** [comment] 2024-08-01 15:14
Checked for the deprecated code  and the code is already updated to the the latest, so something else is happening. Removed the config slash command for now and pushed that. Bug sack info would be appreciated even if it looks to be the same.

**Comment by nickylogic** [comment] 2024-08-01 15:24
I just now updated to the latest Incognito Resurrected and installed Bugsack.  There is only one error report in Bugsack, here it is:

```
1x ...nfig-3.0/AceConfigDialog-3.0-60/AceConfigDialog-3.0.lua:1950: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@IncognitoResurrected/Libs/AceConfig-3.0-2/AceConfigDialog-3.0-60/AceConfigDialog-3.0.lua"]:1950: in function `AddToBlizOptions'
[string "@IncognitoResurrected/IncognitoResurrected.lua"]:149: in function <IncognitoResurrected/IncognitoResurrected.lua:133>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
[string "=(tail call)"]: ?
[string "@IncognitoResurrected/Libs/AceAddon-3.0-12/AceAddon-3.0.lua"]:529: in function `InitializeAddon'
[string "@IncognitoResurrected/Libs/AceAddon-3.0-12/AceAddon-3.0.lua"]:644: in function <...ognitoResurrected/Libs/AceAddon-3.0/AceAddon-3.0.lua:636>

Locals:
self = <table> {
 OpenFrames = <table> {
 }
 BlizOptions = <table> {
 }
 Status = <table> {
 }
 frame = Frame {
 }
}
appName = "IncognitoResurrected Options"
name = "IncognitoResurrected"
parent = nil
BlizOptions = <table> {
 IncognitoResurrected Options = <table> {
 }
}
key = "IncognitoResurrected Options"
group = <table> {
 type = "BlizOptionsGroup"
 AceGUIWidgetVersion = 21
 base = <table> {
 }
 events = <table> {
 }
 userdata = <table> {
 }
 children = <table> {
 }
 label = FontString {
 }
 frame = Frame {
 }
 content = Frame {
 }
}
(*temporary) = nil
(*temporary) = Frame {
 obj = <table> {
 }
 name = "IncognitoResurrected"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"
AceConfigDialog = <table> {
 OpenFrames = <table> {
 }
 BlizOptions = <table> {
 }
 Status = <table> {
 }
 frame = Frame {
 }
}
gui = <table> {
 objPools = <table> {
 }
 WidgetBase = <table> {
 }
 counts = <table> {
 }
 LayoutRegistry = <table> {
 }
 WidgetRegistry = <table> {
 }
 WidgetVersions = <table> {
 }
 WidgetContainerBase = <table> {
 }
}
```

**Comment by Starlynk1** [comment] 2024-08-01 16:01
Well, just found that Ace3 looks to be the cause and it was updated. I am updating my Ace3 embeds and will publish again later today. 

I am guessing that I have an addon installed that already has the updated embeds and it is loading before Incognito is. So I am not seeing the errors.

**Comment by Starlynk1** [comment] 2024-08-01 16:11
Uploaded an Alpha release here and on Curseforge. Can you try that and see if the error is gone now. Thanks

**Comment by nickylogic** [comment] 2024-08-01 19:48
The problem is fixed in the Alpha release.  Thanks!

**Comment by Starlynk1** [comment] 2024-08-01 19:50
Thanks for the update, I will push the released version later today. In the meantime, closing this issue.

**Closed by Starlynk1** 2024-08-01 19:50 UTC
Labels: bug
